#!/bin/bash

MYSQL="$(which mysql)"
MYSQLDUMP="$(which mysqldump)"
GZIP="$(which gzip)"
USER="admin"	# DB_USERNAME
PASS="Neutr1n0s" # DB_PASSWORD
HOST="prod.cierubk1wshr.ap-south-1.rds.amazonaws.com" # DB_HOSTNAME
SLACK_URL_TEST=https://hooks.slack.com/services/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
SLACK_URL_PROD=https://hooks.slack.com/services/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

# Backup Dest directory #
DEST="/opt/prod-mysql" #

# Set date in dd-mm-yyyy format
NOW="$(date +"%d-%m-%Y-%R")"
mkdir -p $DEST/$NOW && cd $DEST/$NOW

curl -X POST -H 'Content-type: application/json' --data {\"text\":\"Starting CRM DATA Refresh for" \"$NOW\"}" $SLACK_URL_PROD

## Backup MYSQL DATA ##
curl -X POST -H 'Content-type: application/json' --data '{"text":"Backing up MySQL DATA... "}' $SLACK_URL_PROD
backup_prod() {
$MYSQLDUMP -h $HOST -u $USER -p$PASS payment bank_details_validation > bank_details_validation.sql
}

backup_prod
if [ $? -eq 0 ]
then
        curl -X POST -H 'Content-type: application/json' --data '{"text":"MySQL Prod Data Backup for CRM was successfull !!!"}' $SLACK_URL_PROD
else
        curl -X POST -H 'Content-type: application/json' --data '{"text":"MySQL Prod Data Backup for CRM failed !!!"}' $SLACK_URL_PROD && exit 0
fi
## DW Details ##
USER2="admin"	# DB_USERNAME
PASS2="T@chy0ns1"	# DB_PASSWORD
HOST2="172.31.20.20"	# DB_HOSTNAME
#SLACK_URL=https://hooks.slack.com/services/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


## Truncate older tables from fnocrm DB ##

payment_truncate() {
mysql -h $HOST2 -u $USER2 -p$PASS2<<TRUNCATE_QUERY
use fnocrm;
SET SQL_SAFE_UPDATES = 0;
update fnouser_customer set password = NULL, password = NOT NULL;
TRUNCATE TABLE payment_bank_details_validation;
TRUNCATE_QUERY

}
payment_truncate

if [ $? -eq 0 ]
then
        curl -X POST -H 'Content-type: application/json' --data '{"text":"fnorcm truncate all tables was successfull !!!"}' $SLACK_URL_PROD
else
        curl -X POST -H 'Content-type: application/json' --data '{"text":"fnocrm truncate all tables was failed !!!"}' $SLACK_URL_PROD
fi

curl -X POST -H 'Content-type: application/json' --data '{"text":"Starting MySQL DATA import for CRM Refresh... "}' $SLACK_URL_PROD

## Rename in .SQL files ##

sed -i 's/bank_details_validation/payment_bank_details_validation/g' bank_details_validation.sql

## Import ##
payment_import() {
mysql -h $HOST2 -u $USER2 -p$PASS2 payment < bank_details_validation.sql
}
payment_import

sleep 15

if [ $? -eq 0 ]
then
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Prod to fnorcm data import was successfull !!!"}' $SLACK_URL_PROD
else
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Prod to fnorcm data import failed !!!"}' $SLACK_URL_PROD
fi
sleep 10

exit 0
